version: "3.6"

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    command: /start_prod.sh
    networks:
      - django-nginx
    env_file:
      - ./.envs/.django
    volumes:
      - .:/code
      - django-static:/backend/static
    depends_on:
      - db

  db:
    image: mysql:5.7.22
    build:
      context: .
      dockerfile: compose/mysql/Dockerfile
    container_name: mysql
    env_file:
      - ./.envs/.mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
        - .db_data:/var/lib/mysql
    ports:
        - 33066:3306
    networks:
      - django-nginx

  adminer:
    image: adminer:4.7-standalone
    container_name: adminer
    ports:
      - 8081:8080
    env_file: ./.envs/.adminer
    depends_on:
      - db
    networks:
      - django-nginx

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx
    ports:
      - 80:80
    networks:
      - django-nginx
    volumes:
      - ./nginx/prod.conf:/etc/nginx/nginx.conf:ro
      - django-static:/usr/src/app/static
      - ./backend/media:/usr/src/app/media:ro
    depends_on:
      - backend
    environment:
      - NODE_OPTIONS=--max_old_space_size=4096

volumes:
  django-static:
  django-media:

networks:
  django-nginx:
    driver: bridge
