# Generated by Django 2.2.1 on 2021-07-04 10:02

import categorybox.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorybox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=categorybox.models.upload_location_category, verbose_name='画像'),
        ),
    ]
