# Generated by Django 2.2.1 on 2021-07-01 10:06

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='氏名')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス')),
                ('message', models.TextField(verbose_name='内容')),
                ('code', models.CharField(max_length=255, verbose_name='番号')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=0, help_text='Active->返事, Inactive->未返事', null=True, verbose_name='状態')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
            options={
                'verbose_name_plural': 'お問い合せ',
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス')),
                ('user_name', models.CharField(max_length=150, unique=True, verbose_name='ユーザー名')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='氏名')),
                ('image', models.ImageField(blank=True, null=True, upload_to=users.models.upload_location, verbose_name='画像')),
                ('birthday', models.DateField(default=None, null=True, verbose_name='誕生日')),
                ('gender', models.IntegerField(blank=True, choices=[(1, '男性'), (2, '女性')], default=1, null=True, verbose_name='性別')),
                ('is_staff', models.BooleanField(default=False, verbose_name='スタッフ')),
                ('is_active', models.BooleanField(default=True, verbose_name='状態')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'ユーザー',
            },
        ),
    ]
