# Generated by Django 2.2.1 on 2021-07-02 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210701_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='is_active',
            field=models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=0, help_text='Active->返答, Inactive->未返答', null=True, verbose_name='状態'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='返答日'),
        ),
    ]
