FROM mysql:5.7.22

#COPY ./compose/mysql/maintenance /usr/local/bin/maintenance
#RUN chmod +x /usr/local/bin/maintenance/*
#RUN cp -r /usr/local/bin/maintenance/* /usr/local/bin && rm -R /usr/local/bin/maintenance

#今、更新中。。
